project_id = "ivsorhhtsyreqyoiygsu"
[functions.create-certificate]
enabled = true
verify_jwt = true
import_map = "./functions/create-certificate/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-certificate/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-certificate/*.html" ]

[functions.update-delete-policy]
enabled = true
verify_jwt = true
import_map = "./functions/update-delete-policy/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/update-delete-policy/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/update-delete-policy/*.html" ]

[functions.verify-certificate]
enabled = true
verify_jwt = false
import_map = "./functions/verify-certificate/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/verify-certificate/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/verify-certificate/*.html" ]
